import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import { getSeverityClass, formatDateTime, formatConfidence } from "@/lib/utils";
import type { Severity } from "@/types";
import type { Metadata } from "next";

interface Props { params: Promise<{ token: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { token } = await params;
  return { title: `Plant Scan Report — PlantAI`, description: `Shared plant disease scan report.` };
}

export default async function SharePage({ params }: Props) {
  const { token } = await params;
  const supabase = await createClient();

  const { data: link } = await (supabase as any)
    .from("share_links")
    .select("*, scans(*)")
    .eq("token", token)
    .single();

  if (!link) return notFound();
  if (link.expires_at && new Date(link.expires_at) < new Date()) return notFound();

  const scan = link.scans as any;

  return (
    <div style={{ minHeight: "100vh", background: "var(--color-bg)", padding: "2rem 1rem" }}>
      <div style={{ maxWidth: 640, margin: "0 auto" }}>
        {/* Header */}
        <div style={{ display: "flex", alignItems: "center", gap: "0.625rem", marginBottom: "2rem" }}>
          <div style={{ width: 32, height: 32, background: "var(--color-primary)", borderRadius: "8px", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <span style={{ fontSize: "1rem" }}>🌿</span>
          </div>
          <span style={{ fontWeight: 700, fontSize: "1rem" }}>PlantAI</span>
          <span style={{ marginLeft: "auto", fontSize: "0.75rem", color: "var(--color-muted)", background: "rgba(82,183,136,0.1)", padding: "0.25rem 0.625rem", borderRadius: 999, border: "1px solid rgba(82,183,136,0.2)" }}>
            Read-only report
          </span>
        </div>

        <div className="card" style={{ padding: 0, overflow: "hidden", marginBottom: "1rem" }}>
          {scan.image_url && (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={scan.image_url} alt="Plant scan" style={{ width: "100%", height: 240, objectFit: "cover" }} />
          )}
          <div style={{ padding: "1.5rem" }}>
            <div style={{ display: "flex", gap: "0.75rem", alignItems: "center", marginBottom: "1rem", flexWrap: "wrap" }}>
              {scan.severity && <span className={getSeverityClass(scan.severity as Severity)}>{scan.severity} severity</span>}
              <span style={{ fontSize: "0.8125rem", color: "var(--color-muted)" }}>{formatDateTime(scan.created_at)}</span>
            </div>
            <h1 style={{ fontSize: "1.375rem", fontWeight: 700, marginBottom: "0.875rem" }}>{scan.disease_name}</h1>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.375rem", fontSize: "0.8125rem", color: "var(--color-muted)" }}>
              <span>Confidence</span>
              <span style={{ color: "var(--color-text)", fontWeight: 600 }}>{scan.confidence ? formatConfidence(scan.confidence) : "—"}</span>
            </div>
            <div style={{ height: 8, background: "var(--color-border)", borderRadius: 4, overflow: "hidden" }}>
              <div style={{ height: "100%", width: `${(scan.confidence || 0) * 100}%`, background: "linear-gradient(90deg, var(--color-primary), var(--color-accent))", borderRadius: 4 }} />
            </div>
          </div>
        </div>

        <div className="card">
          <h2 style={{ fontWeight: 600, marginBottom: "1rem" }}>Treatment Steps</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
            {(scan.treatment_steps || []).map((step: string, i: number) => (
              <div key={i} style={{ display: "flex", gap: "0.75rem", padding: "0.75rem", background: "var(--color-surface-2)", borderRadius: "var(--radius-sm)", fontSize: "0.875rem" }}>
                <span style={{ width: 22, height: 22, background: "var(--color-primary)", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, fontSize: "0.75rem", fontWeight: 700, color: "#fff" }}>{i + 1}</span>
                {step}
              </div>
            ))}
          </div>
        </div>

        <div style={{ textAlign: "center", marginTop: "2rem", color: "var(--color-muted)", fontSize: "0.8125rem" }}>
          Generated by <span style={{ color: "var(--color-accent)", fontWeight: 500 }}>PlantAI</span> · AI-powered plant disease detection
        </div>
      </div>
    </div>
  );
}
