# Treatment map for all 38 PlantVillage disease classes
# Key: exact label from linkanjarad/mobilenet_v2_1.0_224-plant-disease-classification
# Value: list of treatment steps

TREATMENT_MAP: dict[str, list[str]] = {
    "Apple___Apple_scab": [
        "Remove and destroy all infected leaves and fruit — do not compost them.",
        "Apply a fungicide containing captan, mancozeb, or myclobutanil at 7–10 day intervals.",
        "Prune trees to improve air circulation and reduce moisture retention.",
        "Rake and remove fallen leaves from the base of the tree each autumn.",
        "Plant scab-resistant apple varieties for future seasons.",
    ],
    "Apple___Black_rot": [
        "Remove mummified (dried) fruit and cankers from branches immediately.",
        "Apply copper-based fungicide or captan during the growing season.",
        "Prune any dead or dying branches at least 15cm below visible infection.",
        "Maintain good orchard hygiene — remove debris from the ground.",
        "Avoid injuring fruit during harvest as wounds allow entry.",
    ],
    "Apple___Cedar_apple_rust": [
        "Apply myclobutanil or mancozeb fungicide starting at pink bud stage.",
        "Remove nearby eastern red cedar trees (Juniperus virginiana) if possible — they are the alternate host.",
        "Spray every 7–10 days during wet periods in spring.",
        "Plant rust-resistant apple varieties where possible.",
        "Monitor and remove galls from cedars in late winter before spring rains.",
    ],
    "Apple___healthy": [
        "Your apple plant appears healthy — no treatment needed.",
        "Continue regular monitoring every 7 days.",
        "Maintain good pruning practices for air circulation.",
        "Apply preventive fungicide sprays if wet weather is forecast.",
    ],
    "Blueberry___healthy": [
        "Your blueberry plant appears healthy — no treatment needed.",
        "Ensure soil pH is between 4.5–5.5 for optimal growth.",
        "Water at the base to avoid wetting foliage.",
        "Apply 5–10cm of pine bark mulch to retain moisture.",
    ],
    "Cherry_(including_sour)___Powdery_mildew": [
        "Apply sulfur fungicide or potassium bicarbonate at first sign of infection.",
        "Remove and destroy heavily infected leaves and shoots.",
        "Increase air circulation through pruning.",
        "Avoid overhead irrigation — water at the base.",
        "Apply fungicide every 10–14 days until symptoms resolve.",
    ],
    "Cherry_(including_sour)___healthy": [
        "Your cherry plant appears healthy — no treatment needed.",
        "Continue regular inspection, especially during warm humid periods.",
        "Prune annually to maintain open canopy and air flow.",
    ],
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": [
        "Apply fungicide containing strobilurin or triazole at early tasseling.",
        "Rotate crops — avoid planting maize in the same field 2 years in a row.",
        "Plant resistant hybrids where gray leaf spot is a recurring problem.",
        "Minimize tillage to reduce infected residue on the soil surface.",
        "Remove and destroy heavily infected plant debris after harvest.",
    ],
    "Corn_(maize)___Common_rust_": [
        "Apply triazole or strobilurin fungicide early when pustules first appear.",
        "Plant rust-resistant maize varieties.",
        "Monitor fields weekly during warm, humid conditions.",
        "Early infection causes more damage — act within 3–5 days of first symptoms.",
    ],
    "Corn_(maize)___Northern_Leaf_Blight": [
        "Apply fungicide (azoxystrobin, propiconazole) at tasseling stage.",
        "Rotate crops and avoid continuous maize production in the same field.",
        "Use resistant hybrids as the primary management tool.",
        "Bury or incorporate residue after harvest to reduce inoculum.",
    ],
    "Corn_(maize)___healthy": [
        "Your maize plant appears healthy — no treatment needed.",
        "Continue scouting weekly during the growing season.",
        "Maintain proper spacing for air circulation.",
    ],
    "Grape___Black_rot": [
        "Apply mancozeb or myclobutanil fungicide starting at bud break.",
        "Remove and destroy all mummified berries and infected shoots.",
        "Prune vines to improve air circulation and sunlight penetration.",
        "Train vines to minimize contact between fruit and foliage.",
        "Apply fungicide every 10–14 days during wet periods.",
    ],
    "Grape___Esca_(Black_Measles)": [
        "No curative treatment exists — manage to slow progression.",
        "Remove and burn infected vines to prevent spread.",
        "Avoid large pruning wounds — use double pruning technique.",
        "Apply wound sealant immediately after pruning.",
        "Replace severely infected vines with certified disease-free stock.",
    ],
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": [
        "Apply copper-based fungicide or mancozeb at first symptoms.",
        "Improve canopy management through shoot positioning.",
        "Remove infected leaves and dispose of them away from the vineyard.",
        "Avoid excessive nitrogen fertilization which promotes lush growth.",
    ],
    "Grape___healthy": [
        "Your grape vine appears healthy — no treatment needed.",
        "Continue regular monitoring during the growing season.",
        "Maintain proper canopy management for air flow.",
    ],
    "Orange___Haunglongbing_(Citrus_greening)": [
        "CRITICAL: This disease has no cure. Infected trees must be removed and destroyed.",
        "Remove infected trees immediately to prevent spread by psyllid insects.",
        "Apply systemic insecticides to control the Asian citrus psyllid vector.",
        "Do not move plant material from infected areas.",
        "Contact your local agricultural department — this is a notifiable disease in many countries.",
    ],
    "Peach___Bacterial_spot": [
        "Apply copper-based bactericide starting at bud swell in spring.",
        "Avoid overhead irrigation to reduce leaf wetness periods.",
        "Prune infected twigs 15–20cm below visible symptoms.",
        "Plant resistant varieties where bacterial spot is prevalent.",
        "Apply bactericide every 7–10 days during wet weather.",
    ],
    "Peach___healthy": [
        "Your peach tree appears healthy — no treatment needed.",
        "Continue regular monitoring and preventive spray program.",
        "Thin fruit to prevent overcrowding and disease entry.",
    ],
    "Pepper,_bell___Bacterial_spot": [
        "Apply copper-based bactericide at first sign of symptoms.",
        "Remove and destroy infected plant material immediately.",
        "Avoid working in fields when plants are wet.",
        "Use drip irrigation instead of overhead sprinklers.",
        "Rotate with non-solanaceous crops for at least 2 years.",
    ],
    "Pepper,_bell___healthy": [
        "Your pepper plant appears healthy — no treatment needed.",
        "Monitor weekly for early signs of disease.",
        "Maintain consistent soil moisture to avoid stress.",
    ],
    "Potato___Early_blight": [
        "Apply fungicide containing chlorothalonil or mancozeb at canopy closure.",
        "Remove and destroy lower infected leaves to slow disease spread.",
        "Avoid overhead irrigation — water in the morning so foliage dries quickly.",
        "Ensure adequate soil calcium and avoid excessive nitrogen.",
        "Rotate crops — avoid potatoes or tomatoes in the same field for 3 years.",
    ],
    "Potato___Late_blight": [
        "URGENT: Apply systemic fungicide (metalaxyl or cymoxanil) within 24 hours.",
        "Remove and bag all infected plant material — do not compost.",
        "Apply preventive copper-based fungicide to healthy surrounding plants.",
        "Destroy all plant debris immediately after harvest.",
        "Do not store tubers showing signs of infection.",
        "Notify neighboring farmers — late blight spreads rapidly by wind.",
    ],
    "Potato___healthy": [
        "Your potato plant appears healthy — no treatment needed.",
        "Continue regular monitoring, especially during cool wet weather.",
        "Apply preventive fungicide spray if rain is forecast for 3+ consecutive days.",
    ],
    "Raspberry___healthy": [
        "Your raspberry plant appears healthy — no treatment needed.",
        "Prune out old canes after fruiting to improve air circulation.",
        "Maintain weed-free rows to reduce disease pressure.",
    ],
    "Soybean___healthy": [
        "Your soybean plant appears healthy — no treatment needed.",
        "Scout fields weekly for pests and disease signs.",
        "Ensure proper plant spacing for early canopy closure.",
    ],
    "Squash___Powdery_mildew": [
        "Apply potassium bicarbonate or sulfur fungicide at first signs.",
        "Remove severely infected leaves immediately.",
        "Improve air circulation through proper plant spacing.",
        "Water at the base — avoid wetting foliage.",
        "Apply neem oil as an organic alternative every 7 days.",
    ],
    "Strawberry___Leaf_scorch": [
        "Apply fungicide containing captan or myclobutanil.",
        "Remove and destroy infected leaves — do not compost.",
        "Water at the base to keep foliage dry.",
        "Renovate beds after harvest by mowing and thinning.",
        "Plant resistant varieties in future seasons.",
    ],
    "Strawberry___healthy": [
        "Your strawberry plant appears healthy — no treatment needed.",
        "Mulch around plants to prevent soil splash onto leaves.",
        "Remove old leaves and runners regularly.",
    ],
    "Tomato___Bacterial_spot": [
        "Apply copper-based bactericide every 7–10 days during wet weather.",
        "Avoid working in the garden when plants are wet.",
        "Use drip irrigation to keep foliage dry.",
        "Remove and destroy severely infected plants.",
        "Rotate out of solanaceous crops for at least 2 years.",
    ],
    "Tomato___Early_blight": [
        "Apply chlorothalonil or mancozeb fungicide at first symptoms.",
        "Remove lower infected leaves and dispose of in sealed bags.",
        "Mulch around the base to prevent soil splash.",
        "Water at the base in the morning.",
        "Ensure proper plant spacing for air flow.",
    ],
    "Tomato___Late_blight": [
        "URGENT: Apply metalaxyl or cymoxanil fungicide immediately.",
        "Remove all visibly infected plant material and dispose safely — not in compost.",
        "Apply copper-based fungicide to surrounding healthy plants.",
        "Do not water overhead — switch to drip irrigation.",
        "Harvest all mature fruit immediately to prevent tuber infection.",
        "Alert neighboring growers — this disease spreads rapidly.",
    ],
    "Tomato___Leaf_Mold": [
        "Apply fungicide (chlorothalonil, copper, or mancozeb) at first signs.",
        "Reduce humidity in greenhouse environments to below 85%.",
        "Improve ventilation and plant spacing.",
        "Remove and destroy infected leaves.",
        "Avoid overhead watering.",
    ],
    "Tomato___Septoria_leaf_spot": [
        "Apply fungicide (chlorothalonil or copper) at first symptom appearance.",
        "Remove infected lower leaves immediately.",
        "Mulch beneath plants to prevent soil splash.",
        "Rotate crops — do not plant tomatoes in the same spot 2 years in a row.",
        "Water at the base in the morning.",
    ],
    "Tomato___Spider_mites Two-spotted_spider_mite": [
        "Apply miticide (abamectin or spiromesifen) to the underside of leaves.",
        "Spray plants with a strong jet of water to dislodge mites.",
        "Apply neem oil or insecticidal soap as an organic option.",
        "Introduce predatory mites (Phytoseiulus persimilis) as biological control.",
        "Avoid excessive nitrogen fertilization which makes plants more susceptible.",
        "Increase irrigation — mites thrive in dry conditions.",
    ],
    "Tomato___Target_Spot": [
        "Apply fungicide containing azoxystrobin or chlorothalonil.",
        "Remove infected leaves and improve air circulation.",
        "Avoid overhead irrigation.",
        "Rotate with non-solanaceous crops.",
    ],
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": [
        "CRITICAL: No cure exists. Remove and destroy infected plants immediately.",
        "Control whitefly populations with systemic insecticides (imidacloprid).",
        "Use yellow sticky traps to monitor and reduce whitefly numbers.",
        "Use reflective mulch to deter whiteflies.",
        "Plant resistant tomato varieties in future seasons.",
        "Disinfect all tools and equipment after working with infected plants.",
    ],
    "Tomato___Tomato_mosaic_virus": [
        "CRITICAL: No cure. Remove and destroy infected plants immediately.",
        "Disinfect all tools with 10% bleach solution between uses.",
        "Wash hands thoroughly before handling plants.",
        "Control aphid populations which spread the virus.",
        "Plant virus-resistant varieties in future seasons.",
        "Do not smoke near tomato plants — tobacco mosaic virus can spread via tobacco.",
    ],
    "Tomato___healthy": [
        "Your tomato plant appears healthy — no treatment needed.",
        "Continue monitoring weekly, especially during wet or humid weather.",
        "Apply preventive copper spray if late blight is reported in your region.",
        "Stake plants to keep foliage off the ground.",
    ],
}
